[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@astrojs/netlify"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"] 